# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBU3QANwASFhDVXUMa54Ycv6CoIHXUuj
"""

import pandas as pd

# 1. Load the medical dataset
df = pd.read_csv('KaggleV2-May-2016.csv')

# 2. Rename columns to be cleaner and standard
df.columns = df.columns.str.lower().str.replace('-', '_')

# 3. Fix negative ages (anomalies/typos in hospital systems)
df = df[df['age'] >= 0]

# 4. Convert date columns into true Pandas Datetime objects (Removing .dt.date)
df['scheduledday'] = pd.to_datetime(df['scheduledday'])
df['appointmentday'] = pd.to_datetime(df['appointmentday'])

# 5. Calculate "Wait Time" (Now safely outputs Pandas timedelta64[ns])
df['wait_days'] = (df['appointmentday'] - df['scheduledday']).dt.days

# 6. Keep wait days logical (drop instances where appointment is before booking date)
df = df[df['wait_days'] >= 0]

# 7. Save your pristine healthcare data
df.to_csv('clean_hospital_data.csv', index=False)